import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://yabkspuoyjnuiyayfsfn.supabase.co";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhYmtzcHVveWpudWl5YXlmc2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxNzY5NjYsImV4cCI6MjA5Mjc1Mjk2Nn0.eCGuubQV3afnllze_6cq5FJOH2jy-sFkl4WICWwFNyI";

if (!import.meta.env.VITE_SUPABASE_URL || (!import.meta.env.VITE_SUPABASE_ANON_KEY && !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)) {
  console.warn('Missing Supabase environment variables in src/lib/supabase.ts');
}

export const supabase = createClient(supabaseUrl || '', supabaseAnonKey || '', {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});

// Database type exports will be auto-generated by Lovable Cloud
export type { Database } from '@/integrations/supabase/types';
